#!/bin/sh

DIR="$XDG_CONFIG_HOME/eww/bar"

case $1 in
    "get-icon")
        case "$(pactl info | grep "Default Sink:" | cut -d' ' -f3)" in
            "alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1")
                echo "奔";;
            "alsa_output.pci-0000_00_1f.3.analog-stereo")
                echo "";;
        esac;;

    "get-volume")
        pamixer --get-volume
        ;;

    "update-volume-vol")
        eww -c $DIR update volume_vol="$("$DIR"/scripts/volume get-volume)";;
    "update-volume-icon")
        eww -c $DIR update volume_icon="$("$DIR"/scripts/volume get-icon)";;
esac
