#!/bin/bash

workspaces () {
    ws=$(bspc query -D --names | sort)

    declare -A icon
    icon[1]="1"
    icon[2]=""
    icon[3]="3"
    icon[4]="4"
    icon[5]="5"
    icon[6]="6"
    icon[7]="7"
    icon[8]="8"
    icon[9]="9"

    echo -n "(box :class \"workspaces\" :orientation \"horizontal\" "
    echo -n ":space-evenly true :spacing 10 "
    echo -n ":halign \"center\" :space-evenly true :spaceing 10 "

    for i in $ws; do
        state=$(bspc wm --get-status | sed 's/:/\n/g' | grep -G "^.$i")
        case $state in
            "O$i" | "F$i")
                echo -n "(button :onclick \"bsp_desktop_switcher $i\" \
                    :class \"foc\" \"${icon[$i]}\") ";;
            "o$i")
                echo -n "(button :onclick \"bsp_desktop_switcher $i\" \
                    :class \"occ\" \"${icon[$i]}\") ";;
            "f$i")
                echo -n "(button :onclick \"bsp_desktop_switcher $i\" \
                    :class \"emt\" \"${icon[$i]}\") ";;
            "u$i")
                echo -n "(button :onclick \"bsp_desktop_switcher $i\" \
                    :class \"urg\" \"${icon[$i]}\") ";;
        esac
    done

    echo ")"
}

workspaces
bspc subscribe desktop node_transfer | while read -r _ ; do
workspaces
done

