set nocompatible
set t_RV=
filetype off
set encoding=utf-8


"====================PLUGIN MANAGER====================#
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Basic
Plugin 'VundleVim/Vundle.vim'
Plugin 'itchyny/lightline.vim'


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" :PluginInstall

"====================GENERAL====================#
" Basic 
set ruler               " show the cursor position below
set number              " show line number on left side
set showcmd             " show incomplete commad in last line
set cursorline          " highlight cursor line
set laststatus=2        " always show statusline
set scrolloff=3         " keep 3 line when scrolling

" Theme
set background=dark     " dark back ground
colorscheme lucius      " theme
syntax enable           " open syntax highlight

" Search
set hlsearch            " highlight search result
set incsearch           " do incremental searching
set ignorecase          " ignore case when searching, use \c turn off
set smartcase           " no ignorecase if uppercase char present

" Indent
set shiftwidth=4        " indent width
set softtabstop=4       " tab width
set expandtab           " tab always insert softtabstop of amonut spaces 
set autoindent          " copy the indentation of the previous line
set smartindent         " auto indent to next level, work on C-like file
set shiftround          " round the indentation to the nearest multiple of shiftwidth


" Misc
set nobackup            " not keep the backup file

set showmatch           " when you insert bracket, 
set matchtime=1         "    the cursor will briefly jump to the matching one

set backspace=indent,eol,start  " make that backspace key work the way it should

set linebreak           " if text warp, no break on word

set novisualbell        " turn off visual bell
set visualbell t_vb=    " turn off error beep/flash

set t_Co=256            " set 256 colors if term supports
set t_ut=""

set wildmenu            " show the commom complete list, can use Tab and S-Tab




" not auto comment new line
autocmd filetype * set formatoptions-=c formatoptions-=r formatoptions-=o

" delete extra space
autocmd BufWrite *.cpp,*.h,makefile call DeleteExtraSpaces()
function DeleteExtraSpaces()
    :let b:nline= line('.')
    :%s/\s\+$//e
    :execute "to ".b:nline
endfunction



"====================PLUGIN====================#

"===lightline==="
" Set lightline theme
let g:lightline = { 'colorscheme': 'darcula' } 

set noshowmode          " dont show mode below





