#!/bin/sh

file=$1
w=$2
h=$3
x=$4
y=$5

image() {
    if [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ]; then
        printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
        exit 1
    else
        chafa "$1" -s "$4x"
    fi
}

batorcat() {
    file="$1"
    shift

    if file -i "$file" | grep "charset=binary" > /dev/null 2>&1; then
        if command -v hexyl > /dev/null 2>&1; then
            hexyl --border=none -P "$file"
        fi
    else
        if command -v bat > /dev/null 2>&1; then
            bat --color=always --style=plain --pager=never "$file" "$@"
        else
            cat "$file"
        fi
    fi

}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y'- - "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

case "$(printf "%s\n" "$(readlink -f "$file")" | awk '{print tolower($0)}')" in
    *.tgz|*.tar.gz) tar tzf "$file" ;;
    *.tar.bz2|*.tbz2) tar tjf "$file" ;;
    *.tar.txz|*.txz) xz --list "$file" ;;
    *.tar) tar tf "$file" ;;
    *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$file" ;;
    *.rar) unrar l "$file" ;;
    *.7z) 7z l "$file" ;;
    *.[1-8]) man "$file" | col -b ;;
    *.o) nm "$file";;
    *.torrent) transmission-show "$file" ;;
    *.iso) iso-info --no-header -l "$file" ;;
    *.odt|*.ods|*.odp|*.sxw) odt2txt "$file" ;;
    *.doc) catdoc "$file" ;;
    *.docx) docx2txt "$file" - ;;
    *.xls|*.xlsx)
        ssconvert --export-type=Gnumeric_stf:stf_csv "$file" "fd://1" | batorcat --language=csv
        ;;
    *.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.mka)
        exiftool "$file"
        ;;
    *.pdf)
        [ ! -f "${CACHE}.jpg" ] && \
            pdftoppm -jpeg -f 1 -singlefile "$file" "$CACHE"
        image "${CACHE}.jpg" "$w" "$h" "$x" "$y"
        ;;
    *.epub)
        [ ! -f "$CACHE" ] && \
            epub-thumbnailer "$file" "$CACHE" 1024
        image "$CACHE" "$w" "$h" "$x" "$y"
        ;;
    *.cbz|*.cbr|*.cbt)
        [ ! -f "$CACHE" ] && \
            comicthumb "$file" "$CACHE" 1024
        image "$CACHE" "$w" "$h" "$x" "$y"
        ;;
    # *.html)
    #     [ ! -f "$CACHE" ] && \
    #         wkhtmltopdf "$file" - | pdftoppm -jpeg -f 1 -singlefile - "$CACHE"
    #     image "${CACHE}.jpg" "$w" "$h" "$x" "$y"
    #     ;;
    *.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
        [ ! -f "${CACHE}.jpg" ] && \
            ffmpegthumbnailer -i "$file" -o "${CACHE}.jpg" -s 0 -q 5
        image "${CACHE}.jpg" "$w" "$h" "$x" "$y"
        ;;
    *.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp|*.gif|*.jfif)
        image "$file" "$w" "$h" "$x" "$y"
        ;;
    *.ino)
        batorcat --language=cpp "$file"
        ;;
    *.ttf|*.otf)
        [ ! -f "${CACHE}.png" ] && \
            fontimage "$file" -o "${CACHE}.png" \
              --text "$(echo $file | awk -F/ '{print $NF}')" \
              --text "abcdefghijklmnopqrstuvwxyz" \
              --text "ABCDEFGHIJKLMNOPQRSTUVWXYZ" \
              --text "0123456789!@#\$%^&*()" > /dev/null
        image "${CACHE}.png" "$w" "$h" "$x" "$y"
        ;;
    *)
        batorcat "$file"
        ;;
esac
exit 0
