#!/bin/sh

run() {
	if [ -x "$(which "$1")" ] && ! pidof -q "$1"; then
		"$@" &
	fi
}

case $(cat /etc/hostname) in
uicom)
	# Set screen to 144 rate
	xrandr --output HDMI-0 --mode 1920x1080 --rate 144.00
	# Tablet driver
	run otd
	;;
uilap)
	;;
esac


# No screen saver
xset s off
xset -dpms

# Remap caps lock to Ctrl
setxkbmap -option ctrl:nocaps
# Input method
run fcitx5 -d

xrdb -load "$XDG_CONFIG_HOME"/X11/xresources
setwallpaper

# start audio
setsid -f start-pipewire

# Startup app
#run dunst
run xcompmgr -n
run unclutter

run syncthing serve --no-browser --no-default-folder
run entr-list

while true; do
	killall dwmblocks >/dev/null 2>&1
	dwmblocks &

	dwm
done
