#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/xresources
if [ -f "$userresources" ]; then
  if [ -f "$(which merge-xresources)" ]; then
    merge-xresources
  else
    xrdb -merge "$userresources"
  fi
fi

usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# set wacom area
if [$(xinput list | grep 'Wacom')]; then
  xsetwacom set "Wacom One by Wacom S Pen stylus" Area 15200 9500 0 4275
fi

# Remap caps lock to Ctrl
setxkbmap -option ctrl:nocaps

# Set screen to 144 rate
xrandr --output HDMI-0 --mode 1920x1080 --rate 144.00

# No screen saver
xset s off
xset -dpms

# Startup app
pgrep "$BROWSER" > /dev/null || $BROWSER &

while true; do
  # Start regular thing
  pgrep "nitrogen" > /dev/null || nitrogen --restore &
  pgrep "sxhkd" > /dev/null || sxhkd &
  # pgrep "picom" > /dev/null || picom $picom_conf --experimental-backend &

  case $WM in
    bspwm)
      bspwm ;;
    leftwm)
      dbus-launch leftwm ;;
    dwm)
      pgrep "picom" > /dev/null || picom --inactive-dim 0.1 --corner-radius 0 --experimental-backend &
      dwmbar &
      dwm ;;
  esac
done
