#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/xresources
usermodmap=$XDG_CONFIG_HOME/X11/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi



#remap ELECOM HUGE
ELE_HUGE_ID=$(xinput list | grep -e 'ELECOM' -e 'HUGE' |\
    head -n 1 | sed -r 's/.*id=([0-9]+).*/\1/')
if [$ELE_HUGE_ID]; then
    xinput --set-button-map ${ELE_HUGE_ID} 1 2 2 3 4 5 6 7 8 9 10 11 3
fi 

#===Start some programs===#
nitrogen --restore &
picom &

#===Start Window Manager===#
#exec xmonad
#exec i3
exec qtile start
