#!/bin/bash

EWW="eww -c $HOME/.config/bspwm/eww/bar"



calendar() {
    LOCK_FILE="$HOME/.cache/eww-calendar.lock"

    run() {
        ${EWW} open calendar
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE" ]]; then
        ${EWW} close audio
        touch "$LOCK_FILE"
        run && echo "ok good!"
    else
        ${EWW} close calendar
        rm "$LOCK_FILE" && echo "closed"
    fi
}




case $1 in
    "calendar") calendar;;
esac
