#!/bin/sh

bspc rule -r "*"


#==================== MONITOR ====================#
bspc monitor HDMI-0 -d 1 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 2


#==================== CONFIG ====================#
bspc config focus_follows_pointer   true


# Border and gap
bspc config border_width            2
bspc config window_gap              12

bspc config focused_border_color    $(xrdb -get color5)
bspc config active_border_color     $(xrdb -get color0)
bspc config normal_border_color     $(xrdb -get color0)


#==================== RULE ====================#
bspc rule -a *:floating:*       state=floating
bspc rule -a *:scratchpad:*     state=floating

bspc rule -a QjackCtl           state=floating
bspc rule -a Pavucontrol        state=floating
bspc rule -a Surf               state=tiled focus=off
bspc rule -a Zathura            state=tiled
bspc rule -a matplotlib         state=floating

bspc rule -a discord            desktop='9'


#==================== STARTUP ====================#
# Basic programs
sxhkd -c ~/.config/bspwm/sxhkdrc &
pgrep "nitrogen" || nitrogen --restore &
pgrep "picom" || picom --experimental-backend &

# Bar
~/.config/eww/launch

# Change cursor
xsetroot -cursor_name left_ptr &

# Auto start programs if the programs not running
pgrep "$BROWSER" || (bspc rule -a $BROWSER -o desktop='1'; $BROWSER &)
pgrep "$TERMINAL" || (bspc rule -a '*' -o desktop='2'; $TERMINAL -e tmux &)
#pgrep "$TERMINAL" || (bspc rule -a '*' -o desktop='2'; $TERMINAL -e tmuxinator start main &)
