#!/bin/sh

bspc rule -r "*"

# Startup
sxhkd -c ~/.config/bspwm/sxhkdrc &
~/.config/polybar/launch.sh

# Monitor
bspc monitor HDMI-0 -d 1 3 4 5 6 7 8 9
bspc monitor HDMI-1 -d 2

bspc config border_width            2
bspc config window_gap              8

bspc click_to_focus                 true


bspc config focused_border_color    $(xrdb -get color5)
bspc config active_border_color     $(xrdb -get color0)
bspc config normal_border_color     $(xrdb -get color0)
