#!/usr/bin/env bash

get_options() {
    echo "  Power"
    echo "  VimWiki"
    echo "  Screen Shot"
}

main() {
    # Get choice from rofi
    choice=$( (get_options) | rofi -dmenu -i -theme ui_theme -p '')

    # If user has not picked anything, exit
    if [[ -z "${choice// }" ]]; then
        exit 1
    fi

    # Run the selected command
    case $choice in
        "  Power")
            rofi -show power -modi power:power-menu -theme ui_theme
            ;;

        "  VimWiki")
            # Check not in group '7'
            if [ -z "$(qtile cmd-obj -o group -f info | grep "'name': '7'")" ]
            then
                qtile cmd-obj -o screen -f toggle_group -a "7"
            fi

            # Check vimwiki not open
            if [ -z "$(ps -ef | grep /vimwiki | grep -v grep)" ]
            then
                alacritty -e nvim ~/vimwiki/index.md
            fi
            ;;

        "  Screen Shot")
            rofi-screenshot
            ;;
    esac

    set -e
}

main $1 &

exit 0

!/bin/bash
