#!/usr/bin/env bash

get_options() {
    echo "  Power"
    echo "  Screen Shot"
}

main() {
    # Get choice from rofi
    choice=$( (get_options) | rofi -dmenu -i -theme ui_theme -p '')

    # If user has not picked anything, exit
    if [[ -z "${choice// }" ]]; then
        exit 1
    fi

    # Run the selected command
    case $choice in
        "  Power")
            rofi -show power -modi power:power-menu -theme ui_theme
            ;;
        "  Screen Shot")
            rofi-screenshot
            ;;
    esac

    set -e
}

main $1 &

exit 0

!/bin/bash
