#!/bin/bash

for x in ./*.sh
do
  sed '/^#/d; /^test/d; /^unset/d' < "$x" > /tmp/temp
  file_name=$(printf "$x" | sed 's/.*i_//g; s/\.sh//g')
  while read -r line
  do
    if [[ "$line" =~ 'i=' ]]; then
      icon="$(echo "$line" | cut -d"'" -f2)"
    fi

    if [[ "$line" =~ 'i_' ]]; then
      name="$(echo "$line" | sed "s/.*i_\($file_name\|custom\)_\(\w*\)=.*/\2 (\1)/; s/_/ /g")"
    else
      name="no name"
    fi

    echo "$icon" "$name" >> ./nerd_icons

  done < /tmp/temp
done
