#!/bin/sh

desktop=$(bspc query -D --names | sort)
fgO=$(xrdb -get color1)
fgo=$(xrdb -get foreground)
fgf=$(xrdb -get color15)
fgu=$(xrdb -get color8)
bgu=$(xrdb -get color7)


for i in $desktop
do
    state=$(bspc wm --get-status | sed 's/:/\n/g' | grep --regexp="^.[1-9]" | grep "$i")

    if [[ ${state:0:1} == "o" ]]; then
        echo -n "%{F$fgo}"
    elif [[ ${state:0:1} == "O" ]]; then
        echo -n "%{F$fgO}"
    elif [[ ${state:0:1} == "f" ]]; then
        echo -n "%{F$fgf}"
    elif [[ ${state:0:1} == "u" ]]; then
        echo -n "%{F$fgu}"
    fi

    echo -n "%{A1:bsp_desktop_switcher $i:}"
    echo -n "$i"
    echo -n "%{A}%{F-}"
done
